name: CIMore actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install server dependencies
      run: |
        cd server
        pnpm install

    - name: Run server tests
      run: |
        cd server
        pnpm test || echo "No server tests yet"

    - name: Install client dependencies
      run: |
        cd client
        pnpm install

    - name: Run client tests
      run: |
        cd client
        pnpm test -- --watchAll=false
